"""Generate developer NPU verification handoff markdown."""

from __future__ import annotations

from typing import Any

from mcp_hwnative_sys.knowledge import route_task_impl
from mcp_hwnative_sys.paths import load_repos_config


def _task_metadata(repo: str, task_key: str) -> dict[str, Any]:
    config = load_repos_config()
    tasks = config.get("tasks", {})
    repo_tasks = tasks.get(repo, {})
    default_tasks = tasks.get("default", {})
    raw = repo_tasks.get(task_key) or default_tasks.get(task_key)
    if not isinstance(raw, dict):
        return {"command": raw if isinstance(raw, str) else ""}
    return raw


def generate_verify_handoff_impl(
    repo: str,
    branch: str,
    sha: str = "",
    task_type: str = "npu_verify_handoff",
    device_ids: str = "0,1",
    platform: str = "a2a3",
    fork_remote: str = "fork-gbisbas",
) -> dict[str, Any]:
    """Build a copy-paste handoff block for NPU container verification."""
    route = route_task_impl(task_type)
    dev_tasks: list[str] = route.get("developer_verify_tasks", [])

    task_sections: list[str] = []
    for task_ref in dev_tasks:
        if ":" not in task_ref:
            continue
        task_repo, task_name = task_ref.split(":", 1)
        meta = _task_metadata(task_repo, task_name)
        cmd = meta.get("command", "")
        notes: list[str] = []
        if meta.get("container_notes"):
            notes.append(str(meta["container_notes"]))
        if meta.get("warning"):
            notes.append(str(meta["warning"]))
        if meta.get("developer_only"):
            notes.append("developer_only: true")
        arch = meta.get("arch_families")
        if arch:
            notes.append(f"arch_families: {arch}")
        req = meta.get("requires")
        if req:
            notes.append(f"requires: {req}")
        task_sections.append(
            f"### `{task_repo}:{task_name}`\n\n```bash\n{cmd}\n```\n"
            + ("\n".join(f"- {n}" for n in notes) if notes else "")
        )

    sha_line = sha.strip() or "<git rev-parse HEAD after checkout>"
    markdown = f"""# NPU verification handoff

**Repo:** `{repo}`  
**Branch:** `{branch}`  
**SHA to record:** `{sha_line}`  
**Platform:** `{platform}`  
**Devices:** `{device_ids}`

## 1. Environment

Run MCP `ascend_env_check` first. For HCCL multi-rank inside Docker see `hw-native-sys://ascend/hccl_container_checklist`.

```bash
export LD_PRELOAD=${{CANN_HOME}}/aarch64-linux/lib64/libhccl.so   # shell only, before pytest
```

## 2. Checkout and build

```bash
cd {repo}
git fetch {fork_remote} {branch}
git checkout -b verify-{branch.replace("/", "-")} {fork_remote}/{branch}
pip install --no-build-isolation -e ".[dev]"
git rev-parse HEAD
```

## 3. Developer verify tasks

{chr(10).join(task_sections) if task_sections else "_No developer_verify_tasks configured for this route._"}

Example distributed ST override:

```bash
pytest tests/st/distributed/collectives/ -v --platform={platform} --device="{device_ids}"
```

## 4. Handoff back

- Record passing `git rev-parse HEAD` and branch name
- **Do not** open upstream PR unless explicitly requested
- Push only to `{fork_remote}` when asked to land fixes

---
*Generated by hw-native-sys MCP `generate_verify_handoff`*
"""

    return {
        "repo": repo,
        "branch": branch,
        "sha": sha or None,
        "task_type": task_type,
        "platform": platform,
        "device_ids": device_ids,
        "developer_verify_tasks": dev_tasks,
        "markdown": markdown,
    }
